/* autogenerated by Processing revision 1293 on 2026-03-25 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import processing.sound.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class h4_NonlinearExperience_YagmurNamli extends PApplet {

/* vcd436s24 - h4: Nonlinear Experience
 @yagmurnamli
 last update: Apr 16
 "What's In My Backyard?"
 . inspiration: Blue Velvet by David Lynch - https://www.youtube.com/watch?v=BeYx_CBH700&ab_channel=Movieclips
 Cube Escape Game Series - https://www.rustylake.com/room-escape-games/cube-escape-collection.html
 . explanation: a surreal horror experience. use the buttons on scene 1 to jump into other scenes and use the home buttons on each scene to return to scene 1
 
 !!!!WARNING!!!! There are some unexpected jumpscares/sounds.
 
 . media: https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flickr.com%2Fphotos%2Farwing3%2F5036187149%2F&psig=AOvVaw0B4G97Fgk1kRmZQLVPfofq&ust=1713295638344000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCPjUxuD5xIUDFQAAAAAdAAAAABAE
 https://www.stickpng.com/img/people/ears/small-ear
 https://www.rawpixel.com/image/6713474/png-sticker-vintage
 https://www.textures4photoshop.com/tex/isolated-objects/golden-hand-mirror-png.aspx
 https://www.stickpng.com/img/people/victorian-women/beautiful-young-victorian-woman-in-a-white-dress
 https://freepngimg.com/png/153948-grass-free-download-png-hd
 all sound files are from: https://pixabay.com/
 . #todo: reduce the hardcoding, figure out the repetition of images etc. (and use less copy-paste for it), the code is too complicated and long so figure out a way to clearly define some things.
 */

/*
    Scenes:
 1 Ear - > 2, 3, 4, 5
 2 Bugs - > 1
 3 Scissors - > 1
 4 Mirror - > 1
 5 Sky - > 1
 */




SoundFile scream, musicBox, vinyl, bugs, scissors, jumpscare;

PImage ear;
PImage grass;
PImage bug;
PImage scissors1;
PImage scissors2;
PImage mirror;
PImage mirror2;
PImage grassBackyard;
PImage eyes;

float a;

int scene = 1;

int b1x = 370;  // Button 1 x-coordinate
int b1y = 310;  // Button 1 y-coordinate

int b2x = 750;  // Button 2 x-coordinate
int b2y = 310;  // Button 2 y-coordinate

int b3x = 50;  // Button 3 x-coordinate
int b3y = 310;  // Button 3 y-coordinate

int b4x = 400;  // Button 4 x-coordinate
int b4y = 50;  // Button 4 y-coordinate

int hx = 35;  // "Home" button x-coordinate
int hy = 550;  // "Home" button y-coordinate

int bdiameter = 50;  // Button diameter
int hdiameter = 30;  // "Home" button diameter

public void setup() {
  /* size commented out by preprocessor */;
  ear = loadImage("ear.png");
  grass = loadImage("grass.jpg");
  bug = loadImage("bug.png");
  scissors1 = loadImage("scissors1.png");
  scissors2 = loadImage("scissors2.png");
  mirror = loadImage("mirror.png");
  mirror2 = loadImage("mirror2.png");
  grassBackyard = loadImage("grassBackyard.png");
  eyes = loadImage("eyes.png");

  scream = new SoundFile(this, "scream.mp3");
  musicBox = new SoundFile(this, "musicBox.mp3");
  vinyl = new SoundFile(this, "vinyl.mp3");
  bugs = new SoundFile(this, "bugs.mp3");
  scissors = new SoundFile(this, "scissors.mp3");
  jumpscare = new SoundFile(this, "jumpscare.mp3");

  imageMode(CENTER);
  rectMode(CENTER);
  a = height;
}

public void draw() {
  if (scene == 1) {
    drawScene1();
  } else if (scene == 2) {
    drawScene2();
  } else if (scene == 3) {
    drawScene3();
  } else if (scene == 4) {
    drawScene4();
  } else if (scene == 5) {
    drawScene5();
  }
}

public void drawScene1() {
  if (!musicBox.isPlaying() &  !vinyl.isPlaying()) {
    musicBox.loop();
    vinyl.loop();
  }
  frameRate(10);
  tint(0xFF99BFB4);
  image (grass, width/2, height/2);
  tint(0, 150);
  image (ear, width/2, height/2, random(200, 600), random(200, 500));
  tint(0xFF5C877B);
  image (ear, width/2, height/2);
  noStroke();
  if (overCircle(b1x, b1y, bdiameter)) { // BUTTON 1
    fill(100, 0, 0, 85);
  } else {
    fill(0, 60);
  }
  circle(b1x, b1y, bdiameter);

  if (overCircle(b2x, b2y, bdiameter)) { // BUTTON 2
    fill(150, 0, 0, 85);
  } else {
    fill(255, 75);
  }
  circle(b2x, b2y, bdiameter);

  if (overCircle(b3x, b3y, bdiameter)) { // BUTTON 3
    fill(150, 0, 0, 85);
  } else {
    fill(255, 75);
  }
  circle(b3x, b3y, bdiameter);

  if (overCircle(b4x, b4y, bdiameter)) { // BUTTON 4
    fill(150, 0, 0, 85);
  } else {
    fill(255, 75);
  }
  circle(b4x, b4y, bdiameter);

  textSize(12);
  fill(255);
  text("Scene 1", 20, 30);
}

public void drawBug() {
  image(bug, width-random(width), a, 75, 100);
  a = a - random(1, 6);
  rotate(random(50));
}

public void drawScene2() {
  vinyl.pause();
  background(0);
  noStroke();
  if (!bugs.isPlaying()) {
    bugs.loop();
  }
  if (overCircle(hx, hy, hdiameter)) {
    fill(100, 0, 0);
    textSize(100);
    text("TAKE ME OUT!", hx+10, hy);
    if (!scream.isPlaying()) {
      scream.play();
    }
  } else {
    fill(100);
  }
  circle(hx, hy, hdiameter);
  fill(255);
  textSize(12);
  text("Scene 2", 20, 30);
  frameRate(5);
  rotate(random(50));
  tint(100);
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  drawBug();
  if (a < 0) {
    a = height;
  }
}

public void drawScene3() {
  tint(0xFF99BFB4);
  image(grass, width/2, height/2);
  if (overCircle(hx, hy, hdiameter)) {
    fill(100, 0, 0);
  } else {
    fill(100);
  }

  circle(hx, hy, hdiameter);
  fill(255);
  textSize(12);
  text("Scene 3", 20, 30);
  if (overRect(width/2, height/2, scissors1.width, scissors1.height)) {
    if (!scissors.isPlaying()) {
      scissors.play();
    }
    image(scissors2, width/2, height/2, 560*0.8f, 380*0.8f);
    image(scissors2, random(width), random(height), 560*0.5f, 380*0.5f);
    image(scissors1, random(width), random(height), 560*0.5f, 380*0.5f);
    image(scissors2, random(width), random(height), 560*0.1f, 380*0.1f);
    image(scissors1, random(width), random(height), 560*0.1f, 380*0.1f);
    image(scissors2, random(width), random(height), 560*0.7f, 380*0.7f);
    image(scissors1, random(width), random(height), 560*0.7f, 380*0.7f);
    image(scissors2, random(width), random(height), 560*0.3f, 380*0.3f);
    fill(100, 0, 0, 50);
    rect(width/2, height/2, width, height);
  } else {
    image(scissors1, width/2, height/2, 560*0.8f, 380*0.8f);
  }
}

public void drawScene4() {
  tint(0xFF99BFB4);
  image (grass, width/2, height/2);
  if (overCircle(hx, hy, hdiameter)) {
    fill(100, 0, 0);
  } else {
    fill(100);
  }
  circle(hx, hy, hdiameter);
  fill(255);
  textSize(12);
  text("Scene 4", 20, 30);
  image (mirror, width/2, height/2, 500, 500);
  if (overCircle(width/2+10, height/2-100, 100)) {

    if (mousePressed)
      image(mirror2, width/2 + random(-2, 2), height/2 + random(-2, 2), 500, 500);

    for (int i = 0; i < 10; i++) {
      noFill();
      strokeWeight(random(15));
      stroke(100, 0, 0, 75);
      circle(width/2+10, height/2-100, random(70, 800));
    }
  }
}

public void drawScene5() {
  background(0);
  tint(0xFF99BFB4);
  image (grassBackyard, width/2, height/2+50);
  if (overRect(width/2, height/2, scissors1.width, scissors1.height)) {
    image (eyes, width/2 + random(-2, 2), height/2 + random(-2, 2), 500, 500);
    image (grassBackyard, width/2, height/2+50);
    if (!jumpscare.isPlaying()) {
      jumpscare.play(1.5f);
    }
  }
  if (overCircle(hx, hy, hdiameter)) {
    fill(100, 0, 0);
  } else {
    fill(100);
  }
  circle(hx, hy, hdiameter);
  fill(255);
  textSize(12);
  text("Scene 5", 20, 30);
}

public void mousePressed() {
  if (scene == 1) {
    if (overCircle(b1x, b1y, bdiameter)) {
      scene = 2;
      println("go to scene 2");
    }
    if (overCircle(b2x, b2y, bdiameter)) {
      scene = 3;
      println("go to scene 3");
    }
    if (overCircle(b3x, b3y, bdiameter)) {
      scene = 4;
      println("go to scene 4");
    }
    if (overCircle(b4x, b4y, bdiameter)) {
      scene = 5;
      println("go to scene 5");
    }
  } else if (scene == 2) {
    if (overCircle(hx, hy, hdiameter)) {
      scene = 1;
      bugs.pause();
      if (!vinyl.isPlaying()) {
        musicBox.loop();
        vinyl.loop();
      }
      println("back to scene 1");
    }
  } else if (scene == 3) {
    if (overCircle(hx, hy, hdiameter)) {
      scene = 1;
      println("back to scene 1");
    }
  } else if (scene == 4) {
    if (overCircle(hx, hy, hdiameter)) {
      scene = 1;
      println("back to scene 1");
    }
  } else if (scene == 5) {
    if (overCircle(hx, hy, hdiameter)) {
      scene = 1;
      println("back to scene 1");
    }
  }
}

public boolean overRect(float x, float y, float w, float h) {
  // If the (x,y) are inside the rect, return 'true'
  if (mouseX > x && mouseX < x+w &&
    mouseY > y && mouseY < y+h) {
    return true;
  } else {
    return false;
  }
}

public boolean overCircle(float x, float y, float d) {
  // If the (x,y) are inside the circle, return 'true'
  if (dist(mouseX, mouseY, x, y) < d/2) {
    return true;
  } else {
    return false;
  }
}


  public void settings() { size(800, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "h4_NonlinearExperience_YagmurNamli" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
